'use strict';

const transformStudies = (res) => {
  return res.map((val) => {
    return [
      val.nct_id,
      val.nlm_download_date_description,
      val.first_received_date,
      val.last_changed_date,
      val.first_recieved_results_date,
      val.received_results_deposit_date,
      val.study_first_submitted_date,
      val.results_first_submitted_date,
      val.disposition_first_submitted_date,
      val.last_update_submitted_date,
      val.study_first_submitted_qc_date,
      val.study_first_posted_date,
      val.study_first_psot_date_type,
      val.results_first_submitted_qc_date,
      val.results_first_posted_date,
      val.results_first_posted_date_type,
      val.disposition_first_submitted_qc_date,
      val.disposition_first_posted_date,
      val.disposition_first_posted_date_type,
      val.last_update_submitted_qc_date,
      val.last_update_posted_date,
      val.last_update_posted_date_type,
      val.start_month_year,
      val.start_date_type,
      val.start_date,
      val.verification_month_year,
      val.verification_date,
      val.completion_month_year,
      val.completion_date_type,
      val.completion_date,
      val.primary_completion_month_year,
      val.primary_completion_date_type,
      val.primary_completion_date,
      val.target_duration,
      val.study_type,
      val.acronym,
      val.baseline_population,
      val.brief_title,
      val.official_title,
      val.overall_status,
      val.last_known_status,
      val.phase,
      val.enrollment,
      val.enrollment_type,
      val.source,
      val.limitations_and_caveats,
      val.number_of_arms,
      val.number_of_groups,
      val.why_stopped,
      val.has_expanded_access,
      val.expanded_access_type,
      val.expanded_access_type_intermediate,
      val.expanded_access_type_treatment,
      val.has_dmc,
      val.is_fda_regulated_drug,
      val.is_fda_regulated_device,
      val.is_unapproved_device,
      val.is_ppsd,
      val.is_us_export,
      val.biospec_retention,
      val.biospec_description,
      val.plan_to_share_ipd,
      val.plan_to_share_ipd_description,
      val.created_at,
      val.updated_at
    ]
  })
};

module.exports = transformStudies;